import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { useEffect, useRef, useState } from 'react';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

interface CheckboxItem {
  id: number;
  label: string;
  checked: boolean;
}

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [tarea, setTarea] = useState<CheckboxItem[]>([]);

  useEffect(() => {
    const savedTarea = localStorage.getItem('tareaList');
    if (savedTarea) {
      setTarea(JSON.parse(savedTarea));
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('tareaList', JSON.stringify(tarea));
  }, [tarea]);

  const clickCreate = () => {
    const labelText = inputRef.current?.value || '';
    const newTarea: CheckboxItem = {
      id: tarea.length + 1,
      label: labelText,
      checked: false,
    };
    setTarea([...tarea, newTarea]);
    if (inputRef.current) {
      inputRef.current.value = '';
    }
  };

  const toggleCheckbox = (id: number) => {
    setTarea(
      tarea.map((item) =>
        item.id === id ? { ...item, checked: !item.checked } : item
      )
    );
  };

  const clickDelete = () => {
    setTarea(tarea.filter((item) => !item.checked));
  };

  const clickDeleteAll = () => {
    setTarea([]);
  };

  return (
    <>
      <Head>
        <title>Lista Quehaceres</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="back-style">
        <h1 className="header">Lista Quehaceres</h1>
        <div className="components-style">
          <input type="text" ref={inputRef} placeholder="Tarea" />
          <button className="button-style" onClick={clickCreate}>Crear Nuevo</button>
        </div>
        <div className="container">
          <ul>
            {tarea.map((item) => (
              <li key={item.id}>
                <input
                  type="checkbox"
                  checked={item.checked}
                  onChange={() => toggleCheckbox(item.id)}
                />
                <span>{item.label}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="components-style">
          <button className="button-style" onClick={clickDelete}>Eliminar Completados</button>
          <button className="button-style" onClick={clickDeleteAll}>Eliminar Todos</button>
        </div>
      </div>
    </>
  );
}
